inherit_gem:
  rubocop-shopify: rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false