name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'
    services:
      sqlite:
        image: nouchka/sqlite3:latest
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up the database
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate
  
    - name: Run tests with coverage
      run: bundle exec rspec

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
